config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'homes/top'
  get 'home/about' => "homes#about"

  root to: "homes#top"

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }


  delete '/books/:book_id/favorites', to: 'favorites#destroy' ,as: :favorite_delete

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy] do
      member do
        get :follows
        get :followers
      end
    end
  end


  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destory]
    resource :book_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

#=========================自分がフォローしている(active)(following)ユーザーを集める==========================================
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  #フォローする側(active)(following)から見て、フォローされる側(passive)(follower)のユーザーを、中間テーブルを介して集める。
  #なので親(foreign_key)はfollowing_id(フォローする側)

  has_many :followings, through: :active_relationships, source: :follower
  #中間テーブル（active_relationships）を介して、「follower」モデルのUser(フォローされた側)を集めることを「following」と定義。
#======================================================================================================================

#=========================自分をフォローしている(passive)(follower)ユーザーを集める==========================================
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id

  has_many :followers, through: :passive_relationships, source: :following
#======================================================================================================================

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、
    #引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_current_user, only: [:edit, :update]

  def ensure_current_user
    if user_signed_in?
      user = User.find(params[:id])
      if current_user.id !=  user.id
        redirect_to user_path(current_user)
      end
    end
  end


  def index
    if user_signed_in?
    	@users = User.all
    	@user = User.find(current_user.id)
    	@book = Book.new
    else
      redirect_to new_user_session_path
    end
  end

  def show
    if user_signed_in?
    	@user = User.find(params[:id])
      @books = @user.books
    	@book = Book.new
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    if user_signed_in?
  	 @user = User.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
  	@user= User.find(params[:id])
  	if @user.update(user_params)
  	   redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
       render action: :edit
    end
  end


  private

  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body>

	<%= render 'layouts/header' %>

	<div class="container" style="margin-top: 50px;">
		<div class="row">
			<h2>User info</h2>

			<% if @user.errors.any? %>
				<h2 style="color: red;"><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
				<% @user.errors.full_messages.each do |msg| %>
					<li style="color: red;"><%= msg %></li>
				<% end %>
			<% end %>

			<%= form_for(@user) do |f| %>
				<div class="name">
					<p><strong>Name </strong><%= f.text_field :name, class:"", id:"inputEmail", placeholder:"名前"%></p>
				</div>
				<div class="image">
					<p><strong>Image</strong></p>
					<%= f.attachment_field :profile_image, class: "user-edit-form" %>
				</div>
				<div class="Introduction">
					<p><strong>Intoroduction</strong><%= f.text_area :introduction %></p>
				</div>
				<%= f.submit "Update User", class:"submit" %>
			<% end %>
		</div>
	</div>

	<%= render 'layouts/footer' %>


</body>

app/views/users/index.html.erb
<body>

	<%= render 'layouts/header' %>

	<div class="container" style="margin-top: 70px;">
		<div class="row">
			<%= render 'layouts/sidebar' , user: current_user, book: @book %>

			<div class="col-xs-9">
				<h2>Users</h2>
				<table class="table">
					<thead>
						<th>image</th> <th>name</th><th colspan="1"></th>
					</thead>

					<tbody>
					<% @users.each do |user| %>
							<tr>
								<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', fallback: "no_image.jpg", size:'50x50' %></td>
								<td><%= user.name %></td>
								<td>フォロー数： <%= user.active_relationships.count %></td>
								<td>フォロワー数： <%= user.passive_relationships.count %></td>

								<% if current_user != user %>
									<% if user.followed_by?(current_user) %>
									<td><%= link_to 'フォロー中', user_relationships_path(user), method: "delete", class: "btn btn-primary" %></td>
									<% else %>
									<td><%= link_to ' フォロー ', user_relationships_path(user), method: "post", class: "btn btn-info" %></td>
									<% end %>
								<% else %>
									<td></td>
								<% end %>
								<td><%= link_to "Show", user_path(user) %></td>
							</tr>
					<% end %>
					</tbody>
				</table>
			</div>

		</div>

	</div>

	<%= render 'layouts/footer' %>

</body>

app/views/users/show.html.erb
<body>

<%= render 'layouts/header' %>

<div class="container" style="margin-top: 70px;">
	<div class="row">

		<p id="notice" style="color: green;"> <!-- userのサクセスメッセージ -->
			<%= notice %>
		</p>

		<%= render 'layouts/sidebar', user: @user, book: @book %>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<th colspan="1"></th> <th>Title</th> <th>Opinion</th>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(@user) do %>
								<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format:'jpeg', fallback: "no_image.jpg", size:'50x50' %>
								<% end %>
							</td>
							<td><%= link_to book.title,book_path(book.id) %></td>
							<td><%= book.body %></td>

							<td>コメント数：<%= book.book_comments_count.to_i %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>

	</div>

</div>

	<%= render 'layouts/footer' %>


</body>